const fs = require('fs');
const os = require('os');
const path = require('path');

const appRoot = process.cwd();

const packageJsonUrl = path.resolve(`${appRoot}/package.json`);
//const otelJsonUrl = path.resolve(`${appRoot}/node_modules/@opentelemetry/core/package.json`);
const pJson = require(packageJsonUrl);
//const otelJson = require(otelJsonUrl);

// const content = `// this is autogenerated file, see scripts/version-update.js
// export const VERSION = '${pJson.version}';
// export const OTEL_VERSION = '${otelJson.version}';
// `;
const content = `// this is autogenerated file, see scripts/version-update.js
export const VERSION = '${pJson.version}';
`;

const fileUrl = path.join(appRoot, 'src', 'version.ts');

fs.writeFileSync(fileUrl, content.replace(/\n/g, os.EOL));
